### ISSUE TITLE
01. Tìm hiểu các kỹ thuật xây dựng giao diện

### ISSUE THREAD

**Issue by HoangCaoPhi** [HoangCaoPhi/ToeicFun#12]
Các kỹ thuật được áp dụng xây dưng giao diện: HTML, CSS, JavaScrip, Bootstrap...
Mọi người cố gắng học tập ít nhất đến mức cơ bản

**Comment by meomen** [comment]
- [x]  Tìm hiểu HTML

- [x] Tìm hiểu CSS

- [x] Tìm hiểu Bootstrap

- [x] Tìm hiểu JavaScrip

- [x] Tìm hiểu bố cục giao diện của 1 trang web

- [x] Đề xuất , phát thảo ý tưởng làm giao diện

- [x] Chọn lọc từ các ý tưởng, tìm ra 1 quyết định chung
