### ISSUE TITLE
03. Tìm các hình ảnh minh họa liên quan đến các từ vựng

### ISSUE THREAD

**Issue by HoangCaoPhi** [HoangCaoPhi/ToeicFun#17]
Từng từ 1 có 1 hình ảnh đi kèm. Thành viên nhận việc lên google image tra từ để tìm hình ảnh hợp lý.

**Comment by meomen** [comment]
- [x] Lên danh sách các từ vựng nhóm đã thảo luận.

- [x] Tìm kiếm hình ảnh minh họa: Người làm có thể tìm kiếm trên google hình ảnh dựa theo danh sách từ nhóm đã thảo luận.

- [x] Chọn lọc hình ảnh và tạo nên 1 danh sách hình ảnh tương ứng với các từ vựng nhóm đã thảo luận.
