### ISSUE TITLE
02. Xây dựng menu.

### ISSUE THREAD

**Issue by HoangCaoPhi** [HoangCaoPhi/ToeicFun#18]
Thành viên nhận việc xây dựng menu gồm các phần trang chủ, học từ vựng, ngữ pháp,luyện tập.

**Comment by meomen** [comment]
- [x] Liệt kê các phần có trên menu gồm trang chủ, học từ vựng, luyện tập, và ngữ pháp TOEIC

- [x] Responsive menu

- [x] Căn chỉnh lề, màu nền
