### ISSUE TITLE
04. Tạo danh sách các chủ đề từ vựng trong trang chủ

### ISSUE THREAD

**Issue by HoangCaoPhi** [HoangCaoPhi/ToeicFun#19]
Thành viên nhận việc lưu ý: có 24 chủ đề, nên chia thành 6 hàng, mỗi hàng có 4 chủ đề theo bộ từ vựng nhóm đã thảo luận.

**Comment by meomen** [comment]
- [x] Liệt kê các chủ đề từ vựng nhóm đã thảo luận.

- [x] Tạo khung danh sách , với 6 hàng 4 cột.

- [x]  Điền từng item chủ đề vào, mỗi item chủ đề bao gồm : dòng tiêu đề ở trên và hình ảnh minh họa chủ đề ở dưới 

- [x] Tạo liên kết cho item chủ đề

- [x] Căn lề danh sách, chỉnh màu nền, tạo khả năng responsive các loại màn hình

- [x] Kiểm tra, chỉnh sửa từ giao diện đến chức năng các item chủ đề
