### ISSUE TITLE
05. Xây dựng các mục ngữ pháp tiếng anh trong phần học ngữ pháp

### ISSUE THREAD

**Issue by HoangCaoPhi** [HoangCaoPhi/ToeicFun#20]
Dựa vào tài liệu ngữ pháp tìm được,phân chia  thành các phần riêng. Rồi nạp thành từng mục trong giao diện học ngữ pháp

**Comment by meomen** [comment]
- [ ] Liệt kê, chia nhóm các ngữ pháp 

- [ ] Tạo bảng ngữ pháp : từng nhóm ngữ pháp tương ứng 1 bảng

- [ ]  Căn lề các bảng, tạo khả năng responsive với các kích thước màn hình
