### ISSUE TITLE
Làm giao diện bên ngoài cho phần luyện tập

### ISSUE THREAD

**Issue by HoangCaoPhi** [HoangCaoPhi/ToeicFun#28]
Bố cục giao diện bao gồm: số câu hỏi, khung câu hỏi, 4 câu trả lời trắc nghiệm,nút trả lời,số điểm hiện có.

- [x] 1. Tạo trang luyentap.html và tạo liên kết với trang đó.

- [x] 2. Tạo 2 phần chính, một phần là hiển thị câu hỏi, một phần hiển thị số điểm.

- [x] 3. Tạo khung câu hỏi ứng với các dạng câu hỏi.

- [x] 4. Tạo phần trả lời trắc nghiệm ứng với các dạng câu hỏi.

- [x] 5.Tạo nút trả lời và ô điểm hiện tại.

**Comment by HoangCaoPhi** [comment]
Tôi nhận công việc 1,2,3

**Comment by meomen** [comment]
Tôi nhận công việc 4,5,6
