### ISSUE TITLE
Làm chức năng bên trong cho phần luyện tập

### ISSUE THREAD

**Issue by HoangCaoPhi** [HoangCaoPhi/ToeicFun#29]
Tạo kho câu hỏi, với các câu hỏi thuộc các dạng: Nhìn nghĩa đoán từ, Nhìn hình đoán từ, Điền từ. Mỗi câu hỏi đi kèm với 1 câu trả lời đúng. Câu hỏi xuất hiện ngẫu nhiên. Mỗi lượt luyện tập có 10 câu hỏi.

- [x] 1. Làm mẫu câu hỏi Nhìn nghĩa đoán từ.

- [x] 2. Làm mẫu câu hỏi Nhìn hình đoán từ.

- [x] 3. Làm mẫu câu hỏi Điền từ.

- [x] 6. Làm khả năng kiểm tra câu trả lời.

**Comment by HoangDTung** [comment]
Tôi nhận công việc 1,2,3,4

**Comment by hieuss99** [comment]
Tôi nhận việc 5,6,7

**Comment by hieuss99** [comment]
Tôi nhận việc 5,6,7

**Comment by HoangDTung** [comment]
bao giờ xong hả sếp, e bị thọt -.- nên làm lâu đấy

Vào CN, 21 thg 4, 2019 vào lúc 16:32 HoangCaoPhi <notifications@github.com>
đã viết:
