### ISSUE TITLE
Tạo hiệu ứng cho phần luyện tập sau mỗi lần trả lời câu hỏi

### ISSUE THREAD

**Issue by HoangCaoPhi** [HoangCaoPhi/ToeicFun#30]
Hiển thị màu đỏ, xanh tương ứng với đúng sai,cộng điểm  khi trả lời đúng

- [x] 1. Khi trả lời đúng, sẽ xuất hiện dấu tích ở đầu và chuyển xanh đáp án đúng ,cộng  1 điểm vào ô điểm.

- [x] 2. Khi trả lời sai, sẽ xuất hiện dấu X ở đầu và chuyển đỏ đáp án sai.  Đáp án câu hỏi sẽ hiện ở dưới phần trả lời.

**Comment by meomen** [comment]
tôi nhận công việc 1,2
